(in-package #:cl-user)

(let* ((writes nil)
       (connection (cl-quic-kit:make-quic-connection
                    :io-write (lambda (ignored bytes)
                                (declare (ignore ignored))
                                (push bytes writes)))))
  (let* ((client (cl-quic-kit:make-quic-client
                  :connection connection
                  :local-connection-id (make-array 8 :element-type '(unsigned-byte 8))
                  :destination-connection-id (make-array 8 :element-type '(unsigned-byte 8))
                  :disable-hostname-verification-p t))
         (stream (cl-quic-kit:client-open-stream client nil))
         (payload (make-array 3 :element-type '(unsigned-byte 8)
                              :initial-contents '(7 8 9))))
    (cl-quic-kit:client-write-stream client stream payload)
    (cl-quic-kit:client-poll client)
    (let ((frame (cl-quic-kit:decode-frame (first writes))))
             (check (and (eq (cl-quic-kit:frame-type frame) :stream)
                  (= (cl-quic-kit:frame-field frame :stream-id) 0)
                  (equalp (cl-quic-kit:frame-field frame :data) payload))
             "client stream writes are encoded through the injected connection I/O"))))

(dolist (size '(65526 65527 65528 1048576))
  (let* ((writes nil)
         (connection (cl-quic-kit:make-quic-connection
                     :io-write (lambda (ignored bytes)
                                 (declare (ignore ignored))
                                 (push bytes writes))))
         (client (cl-quic-kit:make-quic-client
                  :connection connection
                  :local-connection-id (make-array 8 :element-type '(unsigned-byte 8))
                  :destination-connection-id (make-array 8 :element-type '(unsigned-byte 8))
                  :disable-hostname-verification-p t))
         (stream (cl-quic-kit:client-open-stream client nil))
         (payload (make-array size :element-type '(unsigned-byte 8))))
    (dotimes (index size)
      (setf (aref payload index) (mod index 251)))
    (cl-quic-kit:client-write-stream client stream payload :fin-p t)
    (cl-quic-kit:client-flush client)
    (let ((frames (mapcar #'cl-quic-kit:decode-frame (reverse writes)))
          (received (make-array size :element-type '(unsigned-byte 8)
                                :initial-element 0))
          (saw-fin nil))
      (dolist (frame frames)
        (check (<= (length (cl-quic-kit:encode-frame frame))
                   cl-quic-kit::*client-packet-payload-limit*)
               "large stream fragments fit the packet payload budget")
        (let ((data (cl-quic-kit:frame-field frame :data))
              (offset (cl-quic-kit:frame-field frame :offset 0)))
          (replace received data :start1 offset)
          (when (cl-quic-kit:frame-field frame :fin nil)
            (setf saw-fin t))))
      (check (and saw-fin (equalp received payload))
             "large stream data reassembles by stream offset"))))

(let* ((writes nil)
       (connection (cl-quic-kit:make-quic-connection
                   :io-write (lambda (ignored bytes)
                               (declare (ignore ignored))
                               (push bytes writes))))
       (client (cl-quic-kit:make-quic-client
                :connection connection
                :local-connection-id (make-array 8 :element-type '(unsigned-byte 8))
                :destination-connection-id (make-array 8 :element-type '(unsigned-byte 8))
                :disable-hostname-verification-p t))
       (stream (cl-quic-kit:client-open-stream client nil))
       (flow (cl-quic-kit::quic-client-flow-control client))
       (payload (make-array 10 :element-type '(unsigned-byte 8)
                            :initial-contents '(0 1 2 3 4 5 6 7 8 9))))
  (setf (cl-quic-kit::flow-control-state-connection-max-data flow) 4)
  (cl-quic-kit:client-write-stream client stream payload :fin-p t)
  (cl-quic-kit:client-flush client)
  (let ((frames (remove-if-not (lambda (frame)
                                 (eq (cl-quic-kit:frame-type frame) :stream))
                               (mapcar #'cl-quic-kit:decode-frame (reverse writes)))))
    (check (= (length frames) 1) "stream data stops at available connection credit"))
  (cl-quic-kit:flow-control-update-max-data flow 10)
  (cl-quic-kit:client-flush client)
  (let ((frames (remove-if-not (lambda (frame)
                                 (eq (cl-quic-kit:frame-type frame) :stream))
                               (mapcar #'cl-quic-kit:decode-frame (reverse writes)))))
    (check (= (length frames) 2) "pending stream data waits for increased credit")
    (check (and (= (length (cl-quic-kit:frame-field (first frames) :data)) 4)
                (= (length (cl-quic-kit:frame-field (second frames) :data)) 6)
                (cl-quic-kit:frame-field (second frames) :fin))
           "pending stream data resumes with the next offset and FIN")))

(let ((server (cl-quic-kit:make-udp-socket :local-host "127.0.0.1"
                                           :local-port 0
                                           :non-blocking-p nil))
      (client nil))
  (unwind-protect
       (progn
         (setf client
               (cl-quic-kit:make-udp-socket
                :local-host "127.0.0.1" :local-port 0
                :remote-host "127.0.0.1"
                :remote-port (cl-quic-kit:udp-socket-local-port server)
                :non-blocking-p nil))
         (let ((payload (make-array 4 :element-type '(unsigned-byte 8)
                                     :initial-contents '(1 3 3 7))))
           (check (= (cl-quic-kit:udp-send client payload) 4)
                  "UDP sends one complete datagram")
           (multiple-value-bind (received length peer)
               (cl-quic-kit:udp-receive server :wait-p t)
             (check (and (= length 4) (equalp received payload) peer)
                    "UDP receives the datagram and peer address"))))
    (when client (cl-quic-kit:udp-close client))
    (cl-quic-kit:udp-close server)))
