(in-package #:cl-user)

(defun protection-octets (hex)
  (unless (evenp (length hex))
    (error "Hex input has an odd length: ~S" hex))
  (let ((result (make-array (/ (length hex) 2)
                            :element-type '(unsigned-byte 8))))
    (dotimes (i (length result) result)
      (setf (aref result i)
            (parse-integer hex :start (* i 2) :end (+ (* i 2) 2)
                           :radix 16)))))

(defun protection-function (package name)
  (let ((symbol (find-symbol name package)))
    (unless (and symbol (fboundp symbol))
      (error "Required function ~A is unavailable in package ~A"
             name (package-name package)))
    (symbol-function symbol)))

(defun run-protection-tests ()
  (let* ((p (find-package "CL-QUIC-KIT.PROTECTION"))
         (crypto-package (find-package "CRYPTO-KIT")))
    (check (= (funcall (protection-function p "RECONSTRUCT-PACKET-NUMBER") #x9b 1 0)
              #x9b)
           "packet number reconstruction keeps an expected-window candidate")
    (check (= (funcall (protection-function p "RECONSTRUCT-PACKET-NUMBER") #x09 1 #xabe8)
              #xac09)
           "packet number reconstruction selects the previous window")
    (unless crypto-package
      (error "RFC 9001 protection vectors require the cl-crypto-kit provider"))
    (labels ((crypto (name)
               (protection-function crypto-package name)))
      (let* ((provider-constant-time-equal (crypto "CONSTANT-TIME-EQUAL"))
             (constant-time-calls 0))
        (funcall (protection-function p "CONFIGURE-CRYPTO-BACKEND")
                 :hkdf-extract (crypto "HKDF-EXTRACT")
                 :hkdf-expand (crypto "HKDF-EXPAND")
                 :aead-seal (crypto "AEAD-SEAL")
                 :aead-open (crypto "AEAD-OPEN")
                 :aes-ecb (crypto "AES-ENCRYPT-BLOCK")
                 :chacha20 (crypto "CHACHA20-KEYSTREAM")
                 :constant-time-equal
                 (lambda (left right)
                   (incf constant-time-calls)
                   (funcall provider-constant-time-equal left right)))
        (let* ((keys (funcall (protection-function p "DERIVE-INITIAL-SECRETS")
                              (protection-octets "8394c8f03e515708")))
               (client (getf keys :client))
               (server (getf keys :server))
               (server-header (protection-octets
                               "c1000000010008f067a5502a4262b50040750001"))
               (server-payload (protection-octets
                                "02000000000600405a020000560303eefce7f7b37ba1d1632e96677825ddf73988cfc79825df566dc5430b9a045a1200130100002e00330024001d00209d3c940d89690b84d08a60993c144eca684d1081287c834d5311bcf32bb9da1a002b00020304"))
               (server-ciphertext (protection-octets
                                   "5a482cd0991cd25b0aac406a5816b6394100f37a1c69797554780bb38cc5a99f5ede4cf73c3ec2493a1839b3dbcba3f6ea46c5b7684df3548e7ddeb9c3bf9c73cc3f3bded74b562bfb19fb84022f8ef4cdd93795d77d06edbb7aaf2f58891850abbdca3d20398c276456cbc42158407dd074ee"))
               (retry-packet (protection-octets
                              "ff000000010008f067a5502a4262b5746f6b656e"))
               (retry-tag (funcall (protection-function p "RETRY-INTEGRITY-TAG")
                                   retry-packet
                                   :original-destination-connection-id
                                   (protection-octets "8394c8f03e515708"))))
          (check (equalp (getf keys :initial-secret)
                         (protection-octets
                          "7db5df06e7a69e432496adedb00851923595221596ae2ae9fb8115c1e9ed0a44"))
                 "RFC 9001 Appendix A initial secret")
          (check (equalp (funcall (protection-function p "KEY-SET-KEY") client)
                         (protection-octets "1f369613dd76d5467730efcbe3b1a22d"))
                 "RFC 9001 Appendix A client packet key")
          (check (equalp (funcall (protection-function p "KEY-SET-IV") server)
                         (protection-octets "0ac1493ca1905853b0bba03e"))
                 "RFC 9001 Appendix A server packet IV")
          (check (equalp (funcall (protection-function p "KEY-SET-HP") server)
                         (protection-octets "c206b8d9b9f0f37644430b490eeaa314"))
                 "RFC 9001 Appendix A server header protection key")
          (check (equalp (funcall (protection-function p "PROTECT-PAYLOAD")
                                  server 1 server-payload server-header)
                         server-ciphertext)
                 "RFC 9001 Appendix A server AEAD ciphertext")
          (check (equalp (funcall (protection-function p "UNPROTECT-PAYLOAD")
                                  server 1 server-ciphertext server-header)
                         server-payload)
                 "RFC 9001 Appendix A server AEAD opens")
          (let* ((sample (protection-octets "2cd0991cd25b0aac406a5816b6394100"))
                 (protected (funcall (protection-function p "APPLY-HEADER-PROTECTION")
                                     server server-header sample 18 2 t)))
            (check (equalp protected
                           (protection-octets
                            "cf000000010008f067a5502a4262b5004075c0d9"))
                   "RFC 9001 Appendix A server header protection")
            (check (equalp (funcall (protection-function p "REMOVE-HEADER-PROTECTION")
                                    server protected sample 18 2 t)
                           server-header)
                   "header protection removal reverses application"))
          (check (equalp retry-tag
                         (protection-octets "04a265ba2eff4d829058fb3f0f2496ba"))
                 "RFC 9001 Retry integrity tag")
          (check (funcall (protection-function p "VERIFY-RETRY-INTEGRITY")
                          retry-packet retry-tag
                          :original-destination-connection-id
                          (protection-octets "8394c8f03e515708"))
                 "Retry integrity tag verifies")
          (let ((tampered-tag (copy-seq retry-tag)))
            (setf (aref tampered-tag 0) (logxor (aref tampered-tag 0) 1))
            (check (not (funcall (protection-function p "VERIFY-RETRY-INTEGRITY")
                                 retry-packet tampered-tag
                                 :original-destination-connection-id
                                 (protection-octets "8394c8f03e515708")))
                   "Retry integrity rejects a tampered tag"))
          (check (= constant-time-calls 2)
                 "Retry integrity verification uses constant-time comparison"))))))

(run-protection-tests)
