(ignore-errors (require :asdf))
(when (find-package :asdf)
  (ignore-errors (asdf:load-system "cl-crypto-kit")))

(load (merge-pathnames "../package.lisp"
                       (or *load-truename* *default-pathname-defaults*)))

(dolist (file '("src/varint.lisp" "src/packet.lisp" "src/frame.lisp"
                "src/flow-control.lisp" "src/stream.lisp" "src/state.lisp"
                "src/protection.lisp" "src/recovery.lisp"))
  (load (merge-pathnames (concatenate 'string "../" file)
                         (or *load-truename* *default-pathname-defaults*))))

(when (and (find-package "CRYPTO-KIT")
           (find-package "CL-QUIC-KIT.PROTECTION"))
  (let ((p (find-package "CL-QUIC-KIT.PROTECTION"))
        (crypto (lambda (name) (symbol-function (find-symbol name "CRYPTO-KIT")))))
    (funcall (find-symbol "CONFIGURE-CRYPTO-BACKEND" p)
             :hkdf-extract (funcall crypto "HKDF-EXTRACT")
             :hkdf-expand (funcall crypto "HKDF-EXPAND")
             :aead-seal (funcall crypto "AEAD-SEAL")
             :aead-open (funcall crypto "AEAD-OPEN")
             :aes-ecb (funcall crypto "AES-ENCRYPT-BLOCK")
             :constant-time-equal (funcall crypto "CONSTANT-TIME-EQUAL"))))

(in-package #:cl-user)

(defparameter *tests-run* 0)

(defun check (condition description)
  (incf *tests-run*)
  (unless condition
    (error "Test failed: ~A" description)))

(check (= cl-quic-kit:*quic-version-1* #x00000001)
       "QUIC v1 has the RFC 9000 version number")
(check (cl-quic-kit:connection-id-p (make-array 0 :element-type '(unsigned-byte 8)))
       "an empty connection ID is valid")
(check (cl-quic-kit:connection-id-p (make-array 20 :element-type '(unsigned-byte 8)))
       "a twenty-octet connection ID is valid")
(check (not (cl-quic-kit:connection-id-p (make-array 21 :element-type '(unsigned-byte 8))))
       "a twenty-one-octet connection ID is invalid")
(let ((rejected nil))
  (handler-case
      (cl-quic-kit:validate-connection-id "not-octets")
    (cl-quic-kit:invalid-connection-id () (setf rejected t)))
  (check rejected "malformed connection IDs are rejected"))
(let ((encoded (cl-quic-kit:encode-varint 494)))
  (multiple-value-bind (value size) (cl-quic-kit:decode-varint encoded)
    (check (and (= value 494) (= size 2)) "varint round trip")))
(let* ((frame (cl-quic-kit:make-frame :ping))
       (decoded (cl-quic-kit:decode-frame (cl-quic-kit:encode-frame frame))))
  (check (eq (cl-quic-kit:frame-type decoded) :ping) "PING frame round trip"))
(let* ((stream (cl-quic-kit:make-stream 0 :local-initiator :client))
       (payload (make-array 3 :element-type '(unsigned-byte 8)
                            :initial-contents '(1 2 3))))
  (cl-quic-kit:stream-receive-data stream 0 payload :fin t)
  (multiple-value-bind (data fin) (cl-quic-kit:stream-read stream)
    (check (and fin (equalp data payload)) "ordered stream data and FIN")))
(let ((clock 0) (connection nil))
  (setf connection (cl-quic-kit:make-quic-connection
                    :now-fn (lambda () clock) :idle-timeout 10))
  (cl-quic-kit:connection-set-state connection :established)
  (setf clock 10)
  (check (cl-quic-kit:connection-check-idle-timeout connection clock)
         "idle timeout closes established connection"))
(let ((clock 0) (writes nil)
      (cid (make-array 8 :element-type '(unsigned-byte 8) :initial-element 1)))
  (let ((connection (cl-quic-kit:make-quic-connection
                    :local-connection-id cid :now-fn (lambda () clock)
                    :active-connection-id-limit 2
                    :io-write (lambda (connection bytes)
                                (declare (ignore connection))
                                (push bytes writes)))))
    (check (= (length (cl-quic-kit:connection-local-connection-ids connection)) 1)
           "the original connection ID is active")
    (cl-quic-kit:connection-handle-new-connection-id
     connection 1 (make-array 8 :element-type '(unsigned-byte 8) :initial-element 2))
    (check (= (length (cl-quic-kit:connection-remote-connection-ids connection)) 1)
           "NEW_CONNECTION_ID is tracked")
    (cl-quic-kit:connection-handle-new-connection-id
     connection 2 (make-array 8 :element-type '(unsigned-byte 8) :initial-element 3))
    (cl-quic-kit:connection-handle-new-connection-id
     connection 3 (make-array 8 :element-type '(unsigned-byte 8) :initial-element 4))
    (check (eq (cl-quic-kit:connection-state connection) :closing)
           "active connection ID limit starts a transport close")
    (check (= (length writes) 1) "transport close is written through injected I/O")))
(let ((clock 0) (writes nil))
  (let ((connection (cl-quic-kit:make-quic-connection
                    :now-fn (lambda () clock) :idle-timeout 10
                    :io-write (lambda (connection bytes)
                                (declare (ignore connection))
                                (push bytes writes)))))
    (cl-quic-kit:connection-set-state connection :established)
    (cl-quic-kit:connection-close connection 42 "transport failure")
    (check (eq (cl-quic-kit:connection-state connection) :closing)
           "CONNECTION_CLOSE enters closing")
    (check (= (length writes) 1) "CONNECTION_CLOSE uses injected output")
    (cl-quic-kit:connection-receive-frame
     connection (cl-quic-kit:make-frame :application-close :error-code 7 :reason #()))
    (check (eq (cl-quic-kit:connection-state connection) :draining)
           "peer application close enters draining")
    (setf clock 30)
    (check (cl-quic-kit:connection-poll connection clock)
           "draining deadline closes the connection")))
(let ((connection (cl-quic-kit:make-quic-connection :now-fn (lambda () 0)))
      (bad-packet (make-array 1 :element-type '(unsigned-byte 8) :initial-element 255)))
  (check (null (cl-quic-kit:connection-receive-packet connection bad-packet))
         "malformed packet is rejected")
  (check (eq (cl-quic-kit:connection-state connection) :closing)
         "malformed packet schedules CONNECTION_CLOSE"))
(let ((state (cl-quic-kit.recovery:make-recovery-state :clock (lambda () 0))))
  (cl-quic-kit.recovery:on-packet-received state :initial 1)
  (check (cl-quic-kit.recovery:ack-needed-p state :initial :now 0)
         "ack eliciting packet schedules ACK"))
(let ((state (cl-quic-kit.recovery:make-recovery-state :clock (lambda () 0))))
  (cl-quic-kit.recovery:record-sent-packet state :application 1 1200 :sent-at 0)
  (multiple-value-bind (acked lost)
      (cl-quic-kit.recovery:on-ack-frame state :application 1 '((1 1))
                                         :received-at 1/10)
    (check (and (= (length acked) 1) (null lost))
           "ACK acknowledges the largest sent packet")
    (check (and (= (cl-quic-kit.recovery:recovery-state-latest-rtt state) 1/10)
                (= (cl-quic-kit.recovery:recovery-state-smoothed-rtt state) 1/10)
                (= (cl-quic-kit.recovery:recovery-state-rtt-variance state) 1/20)
                (= (cl-quic-kit.recovery:recovery-state-min-rtt state) 1/10))
           "first ACK initializes RTT sample state")))
(let ((state (cl-quic-kit.recovery:make-recovery-state :clock (lambda () 0))))
  (dotimes (number 4)
    (cl-quic-kit.recovery:record-sent-packet state :application (1+ number) 1200
                                             :sent-at 0))
  (multiple-value-bind (acked lost)
      (cl-quic-kit.recovery:on-ack-frame state :application 4 '((4 4))
                                         :received-at 0)
    (check (= (length acked) 1) "packet threshold ACK keeps the largest packet")
    (check (= (length lost) 1) "packet threshold marks packet three numbers behind lost")))
(let ((state (cl-quic-kit.recovery:make-recovery-state :clock (lambda () 1))))
  (cl-quic-kit.recovery:record-sent-packet state :application 1 1200 :sent-at 0)
  (check (= (cl-quic-kit.recovery:loss-timeout state :application)
            (* 9/8 333/1000))
         "loss timeout exposes the earliest time-threshold deadline"))
(let ((state (cl-quic-kit.recovery:make-recovery-state :clock (lambda () 0))))
  (cl-quic-kit.recovery:record-sent-packet state :application 1 1200 :sent-at 0
                                           :ack-eliciting-p nil :in-flight-p nil)
  (check (null (cl-quic-kit.recovery:pto-deadline state :application))
         "non-ack-eliciting packets do not arm PTO")
  (cl-quic-kit.recovery:record-sent-packet state :application 2 1200 :sent-at 0)
  (check (= (cl-quic-kit.recovery:pto-deadline state :application) (* 2 333/1000))
         "initial PTO uses twice the initial RTT")
  (let ((probe (cl-quic-kit.recovery:on-pto-expired state)))
    (check (and (= (getf probe :probe-count) 2)
                (= (getf probe :pto-count) 1))
           "PTO expiry requests two probe packets"))
  (check (= (cl-quic-kit.recovery:pto-deadline state :application)
            (+ (* 2 333/1000) (* 2 333/1000)))
         "PTO deadline doubles after an expiry"))
(let ((state (cl-quic-kit.recovery:make-recovery-state :clock (lambda () 4))))
  (dotimes (number 4)
    (cl-quic-kit.recovery:record-sent-packet state :application (1+ number) 1200
                                             :sent-at number))
  (multiple-value-bind (acked lost)
      (cl-quic-kit.recovery:on-ack-frame state :application 4 '((4 4))
                                         :received-at 4)
    (declare (ignore acked))
    (check (= (length lost) 3) "time-threshold loss reports all overdue packets")
    (check (cl-quic-kit.recovery:recovery-state-persistent-congestion-p state)
           "a loss span of three PTOs enters persistent congestion")
    (check (= (cl-quic-kit.recovery:recovery-state-cwnd state) 2400)
           "persistent congestion reduces cwnd to the minimum window")))
(let ((state (cl-quic-kit.recovery:make-recovery-state :clock (lambda () 0)
                                                        :initial-cwnd 12000)))
  (check (= (progn (cl-quic-kit.recovery:newreno-on-ack state 1200) 13200)
            (cl-quic-kit.recovery:recovery-state-cwnd state))
         "NewReno slow start increases cwnd by acknowledged bytes")
  (cl-quic-kit.recovery:newreno-on-loss state :at 1)
  (check (and (= (cl-quic-kit.recovery:recovery-state-cwnd state) 6600)
              (= (cl-quic-kit.recovery:recovery-state-ssthresh state) 6600))
         "NewReno loss enters congestion avoidance at half cwnd")
  (cl-quic-kit.recovery:newreno-on-ack state 1200 :sent-at 1)
  (check (= (cl-quic-kit.recovery:recovery-state-cwnd state) 6600)
         "ACKs for pre-recovery packets do not grow cwnd")
  (cl-quic-kit.recovery:newreno-on-ack state 1200 :sent-at 2)
  (check (= (cl-quic-kit.recovery:recovery-state-cwnd state) 6818)
         "NewReno congestion avoidance grows cwnd by MSS squared over cwnd"))
(load (merge-pathnames "protection.lisp"
                       (or *load-truename* *default-pathname-defaults*)))
(format t "~D tests passed.~%" *tests-run*)
