(in-package #:cl-quic-kit)

(defstruct (frame (:constructor %make-frame (type fields))) type fields)
(defun make-frame (type &rest fields) (%make-frame type fields))
(defun frame-field (frame key &optional default) (getf (frame-fields frame) key default))

(defparameter *frame-type-codes*
  '((:padding . 0) (:ping . 1) (:ack . 2) (:ack-ecn . 3) (:reset-stream . 4)
    (:stop-sending . 5) (:crypto . 6) (:new-token . 7) (:max-data . 16)
    (:max-stream-data . 17) (:max-streams-bidi . 18) (:max-streams-uni . 19)
    (:data-blocked . 20) (:stream-data-blocked . 21) (:streams-blocked-bidi . 22)
    (:streams-blocked-uni . 23) (:new-connection-id . 24) (:retire-connection-id . 25)
    (:path-challenge . 26) (:path-response . 27) (:connection-close . 28)
    (:application-close . 29) (:handshake-done . 30) (:datagram . 49)))

(defun %frame-error (message) (error 'quic-encoding-error :message message))
(defun %empty-octets () (make-array 0 :element-type '(unsigned-byte 8)))
(defun %frame-octets-value (value)
  (if (typep value '(simple-array (unsigned-byte 8) (*)))
      value
      (make-array (length value) :element-type '(unsigned-byte 8)
                  :initial-contents value)))
(defun %frame-code (type)
  (cond ((and (integerp type) (varint-p type)) type)
        ((cdr (assoc type *frame-type-codes*))) ((eq type :stream) #x08)
        (t (%frame-error "Unknown QUIC frame type"))))
(defun %code-frame (code)
  (or (car (rassoc code *frame-type-codes*)) (if (<= #x08 code #x0f) :stream code)))
(defun %frame-octets (&rest parts)
  (let* ((parts (mapcar #'%frame-octets-value parts))
         (out (make-array (reduce #'+ parts :key #'length :initial-value 0)
                          :element-type '(unsigned-byte 8))) (at 0))
    (dolist (part parts out) (replace out part :start1 at) (incf at (length part)))))
(defun %v* (&rest values) (apply #'%frame-octets (mapcar #'encode-varint values)))
(defun %read-v (bytes at)
  (multiple-value-bind (value size) (decode-varint bytes at) (values value (+ at size))))
(defun %slice (bytes at size)
  (when (or (< at 0) (< size 0) (> at (length bytes)) (> size (- (length bytes) at)))
    (%frame-error "Truncated frame"))
  (values (subseq bytes at (+ at size)) (+ at size)))
(defun %nonnegative (value message)
  (unless (and (integerp value) (varint-p value)) (%frame-error message)) value)
(defun %field-varint (fields key &optional (default 0))
  (%nonnegative (getf fields key default) "Frame field is not a QUIC varint"))
(defun %field-octets (fields key &optional size)
  (let ((value (%frame-octets-value (getf fields key (%empty-octets)))))
    (when (and size (/= size (length value))) (%frame-error "Invalid fixed-size frame field")) value))

(defun %ack-ranges (fields)
  (let ((ranges (getf fields :ranges)))
    (if (null ranges)
        (let ((largest (%field-varint fields :largest-acknowledged))
              (first-length (%field-varint fields :first-range)))
          (when (< largest first-length) (%frame-error "ACK range underflows packet number zero"))
          (values largest first-length 1))
        (progn
          (unless (and (listp ranges) (consp (first ranges))) (%frame-error "ACK must contain a first range"))
          (let* ((first-range (first ranges))
                 (largest (%nonnegative (car first-range) "Invalid largest acknowledged"))
                 (first-length (%nonnegative (cdr first-range) "Invalid ACK range length"))
                 (previous-largest (- largest first-length)))
            (when (< largest first-length) (%frame-error "ACK range underflows packet number zero"))
            (dolist (range (rest ranges))
              (unless (and (listp range) (not (eq (getf range :gap :missing) :missing))
                           (not (eq (getf range :range-length :missing) :missing)))
                (%frame-error "Invalid ACK range"))
              (let* ((gap (%nonnegative (getf range :gap) "Invalid ACK gap"))
                     (range-length (%nonnegative (getf range :range-length) "Invalid ACK range length"))
                     (next-largest (- previous-largest gap 2)))
                (when (< next-largest range-length) (%frame-error "ACK range underflows packet number zero"))
                (setf previous-largest (- next-largest range-length))))
            (values largest first-length (length ranges)))))))


(defun encode-frame (frame)
  (let* ((type (frame-type frame)) (fields (frame-fields frame)) (code (%frame-code type)))
    (when (eq type :stream)
      (setf code (+ #x08 (if (getf fields :fin) 1 0) (if (getf fields :len-present t) 2 0)
                    (if (getf fields :offset) 4 0))))
    (case type
      (:padding (let ((count (getf fields :count 1)))
                  (unless (and (integerp count) (plusp count)) (%frame-error "PADDING count must be positive"))
                  (make-array count :element-type '(unsigned-byte 8) :initial-element 0)))
      ((:ping :handshake-done) (encode-varint code))
      ((:ack :ack-ecn)
       (multiple-value-bind (largest first-length range-count) (%ack-ranges fields)
         (let ((ranges (getf fields :ranges))
               (out (%v* code largest (%field-varint fields :ack-delay) (1- range-count) first-length)))
           (dolist (range (rest ranges))
             (setf out (%frame-octets out (encode-varint (%nonnegative (getf range :gap) "Invalid ACK gap"))
                                      (encode-varint (%nonnegative (getf range :range-length) "Invalid ACK range length")))))
           (if (eq type :ack-ecn)
               (%frame-octets out (%v* (%field-varint fields :ect0) (%field-varint fields :ect1)
                                       (%field-varint fields :ecn-ce))) out))))
      (:reset-stream (%v* code (%field-varint fields :stream-id)
                           (%field-varint fields :application-protocol-error-code)
                           (%field-varint fields :final-size)))
      (:stop-sending (%v* code (%field-varint fields :stream-id)
                           (%field-varint fields :application-protocol-error-code)))
      (:crypto (let ((data (%field-octets fields :data)))
                 (%frame-octets (%v* code (%field-varint fields :offset) (length data)) data)))
      (:new-token (let ((data (%field-octets fields :token)))
                    (when (zerop (length data)) (%frame-error "NEW_TOKEN must not be empty"))
                    (%frame-octets (%v* code (length data)) data)))
      (:stream (let ((data (%field-octets fields :data)))
                 (%frame-octets (%v* code (%field-varint fields :stream-id))
                                (if (getf fields :offset) (encode-varint (%field-varint fields :offset)) (%empty-octets))
                                (if (getf fields :len-present t) (encode-varint (length data)) (%empty-octets)) data)))
      ((:max-data :max-streams-bidi :max-streams-uni :data-blocked
        :streams-blocked-bidi :streams-blocked-uni)
       (%v* code (%nonnegative (or (getf fields :maximum) (getf fields :limit) 0)
                              "Invalid flow-control limit")))
      ((:max-stream-data :stream-data-blocked)
       (%v* code (%field-varint fields :stream-id)
            (%nonnegative (or (getf fields :maximum) (getf fields :limit) 0) "Invalid flow-control limit")))
      (:new-connection-id
       (let ((cid (%field-octets fields :connection-id)) (reset (%field-octets fields :stateless-reset-token 16))
             (sequence (%field-varint fields :sequence)) (retire (%field-varint fields :retire-prior-to)))
         (when (> (length cid) 20) (%frame-error "Connection ID is too long"))
         (when (< sequence retire) (%frame-error "RETIRE_PRIOR_TO exceeds sequence number"))
         (%frame-octets (%v* code sequence retire) (vector (length cid)) cid reset)))
      (:retire-connection-id (%v* code (%field-varint fields :sequence)))
      ((:path-challenge :path-response) (%frame-octets (encode-varint code) (%field-octets fields :data 8)))
      ((:connection-close :application-close)
       (let ((reason (%field-octets fields :reason)))
         (%frame-octets (%v* code (%field-varint fields :error-code))
                        (if (eq type :connection-close)
                            (%frame-octets (%v* (%field-varint fields :frame-type)
                                               (length reason)) reason)
                            (%frame-octets (encode-varint (length reason)) reason)))))
      (:datagram
       (let ((data (%field-octets fields :data)))
         (if (getf fields :len-present t)
             (%frame-octets (encode-varint #x31) (encode-varint (length data)) data)
             (%frame-octets (encode-varint #x30) data))))
      (otherwise (%frame-error "Frame encoding not implemented")))))

(defun decode-frame (bytes &optional (start 0))
  (let* ((b (ensure-octets bytes)) (at start))
    (multiple-value-bind (code next) (%read-v b at)
      (setf at next)
      (labels ((v () (multiple-value-bind (x n) (%read-v b at) (setf at n) x))
               (data (n) (multiple-value-bind (x n2) (%slice b at n) (setf at n2) x)))
        (let ((frame
                (cond
                  ((= code 0) (let ((count 1))
                                (loop while (and (< at (length b)) (zerop (aref b at))) do (incf at) (incf count))
                                (make-frame :padding :count count)))
                  ((= code 1) (make-frame :ping))
                  ((member code '(2 3))
                   (let* ((largest (v)) (delay (v)) (count (v)) (first (v))
                          (ranges (list (cons largest first))) (previous largest))
                     (when (> first largest) (%frame-error "ACK range underflows packet number zero"))
                     (dotimes (i count)
                       (let* ((gap (v)) (range-length (v)) (next-largest (- previous gap 2)))
                         (when (or (< next-largest range-length) (< next-largest 0))
                           (%frame-error "ACK range underflows packet number zero"))
                         (push (list :gap gap :range-length range-length) ranges)
                         (setf previous (- next-largest range-length))))
                     (setf ranges (nreverse ranges))
                     (if (= code 3)
                         (make-frame :ack-ecn :largest-acknowledged largest :ack-delay delay :ranges ranges
                                     :ect0 (v) :ect1 (v) :ecn-ce (v))
                         (make-frame :ack :largest-acknowledged largest :ack-delay delay :ranges ranges))))
                  ((= code 4) (make-frame :reset-stream :stream-id (v) :application-protocol-error-code (v) :final-size (v)))
                  ((= code 5) (make-frame :stop-sending :stream-id (v) :application-protocol-error-code (v)))
                  ((= code 6) (let ((offset (v)) (length (v))) (make-frame :crypto :offset offset :data (data length))))
                  ((= code 7) (let ((length (v))) (when (zerop length) (%frame-error "NEW_TOKEN must not be empty"))
                                 (make-frame :new-token :token (data length))))
                  ((<= #x08 code #x0f) (let ((stream-id (v)) (offset (if (logbitp 2 code) (v) 0))
                                                   (length (if (logbitp 1 code) (v) (- (length b) at))))
                                         (make-frame :stream :stream-id stream-id :offset offset :data (data length)
                                                     :fin (logbitp 0 code) :len-present (logbitp 1 code))))
                  ((<= #x10 code #x17) (make-frame (%code-frame code) :maximum (v)))
                  ((= code #x18) (let ((sequence (v)) (retire (v)))
                                   (when (>= at (length b)) (%frame-error "Missing NEW_CONNECTION_ID length"))
                                   (let ((n (aref b at))) (incf at)
                                     (when (> n 20) (%frame-error "Connection ID is too long"))
                                     (when (< sequence retire) (%frame-error "RETIRE_PRIOR_TO exceeds sequence number"))
                                     (make-frame :new-connection-id :sequence sequence :retire-prior-to retire
                                                 :connection-id (data n) :stateless-reset-token (data 16)))))
                  ((= code #x19) (make-frame :retire-connection-id :sequence (v)))
                  ((member code '(#x1a #x1b)) (make-frame (%code-frame code) :data (data 8)))
                  ((member code '(#x1c #x1d)) (let ((error-code (v)) (frame-type (if (= code #x1c) (v) 0))
                                                        (length (v)))
                                                (make-frame (%code-frame code) :error-code error-code
                                                            :frame-type frame-type :reason (data length))))
                  ((= code #x1e) (make-frame :handshake-done))
                  ((member code '(#x30 #x31)) (let ((length (if (= code #x31) (v) (- (length b) at))))
                                                (make-frame :datagram :data (data length) :len-present (= code #x31))))
                  (t (%frame-error "Unknown or unsupported QUIC frame type")))))
          (values frame at))))))

(defun encode-frames (frames) (apply #'%frame-octets (mapcar #'encode-frame frames)))
(defun decode-frames (bytes &optional (start 0))
  (let ((b (ensure-octets bytes)) (at start) (out '()))
    (loop while (< at (length b)) do
      (multiple-value-bind (frame next) (decode-frame b at) (push frame out) (setf at next)))
    (nreverse out)))
