(in-package #:cl-quic-kit)

(defstruct (frame (:constructor %make-frame (type fields)))
  type fields)

(defun make-frame (type &rest fields) (%make-frame type fields))
(defun frame-field (frame key &optional default) (getf (frame-fields frame) key default))

(defparameter *frame-type-codes*
  '((:padding . 0) (:ping . 1) (:ack . 2) (:ack-ecn . 3) (:reset-stream . 4)
    (:stop-sending . 5) (:crypto . 6) (:new-token . 7) (:max-data . 16)
    (:max-stream-data . 17) (:max-streams-bidi . 18) (:max-streams-uni . 19)
    (:data-blocked . 20) (:stream-data-blocked . 21) (:streams-blocked-bidi . 22)
    (:streams-blocked-uni . 23) (:new-connection-id . 24) (:retire-connection-id . 25)
    (:path-challenge . 26) (:path-response . 27) (:connection-close . 28)
    (:application-close . 29) (:handshake-done . 30) (:datagram . 49)))

(defun %frame-code (type)
  (cond ((and (integerp type) (<= 0 type)) type)
        ((assoc type *frame-type-codes*) (cdr (assoc type *frame-type-codes*)))
        ((eq type :stream) #x08)
        (t (error 'quic-encoding-error :message "Unknown QUIC frame type"))))

(defun %code-frame (code)
  (or (car (rassoc code *frame-type-codes*))
      (if (<= #x08 code #x0f) :stream code)))

(defun %append-vector (list vector) (nconc list (coerce (ensure-octets vector) 'list)))
(defun %encode-varints (&rest values) (apply #'%octets (mapcar #'encode-varint values)))
(defun %read-v (b at) (multiple-value-bind (v n) (decode-varint b at) (values v (+ at n))))
(defun %slice (b at length) (when (> (+ at length) (length b)) (error 'quic-encoding-error :message "Truncated frame")) (values (subseq b at (+ at length)) (+ at length)))

(defun encode-frame (f)
  (let* ((type (frame-type f)) (fields (frame-fields f)) (code (%frame-code type)) (stream-type (and (eq type :stream) (+ 8 (if (getf fields :fin) 1 0) (if (getf fields :len-present t) 2 0) (if (getf fields :offset) 4 0)))))
    (setf code (or stream-type code))
    (case type
      (:padding (make-array (or (getf fields :count) 1) :element-type '(unsigned-byte 8) :initial-element 0))
      ((:ping :handshake-done) (encode-varint code))
      ((:ack :ack-ecn)
       (let ((ranges (getf fields :ranges)) (ecn (eq type :ack-ecn)))
         (unless ranges (setf ranges (list (cons (getf fields :largest-acknowledged 0) (getf fields :first-range 0)))))
         (let ((out (%encode-varints code (getf fields :largest-acknowledged (caar ranges)) (getf fields :ack-delay 0) (1- (length ranges)) (cdar ranges))))
           (dolist (range (cdr ranges)) (setf out (%octets out (encode-varint (getf range :gap)) (encode-varint (getf range :range-length)))))
           (if ecn (%octets out (%encode-varints (getf fields :ect0 0) (getf fields :ect1 0) (getf fields :ecn-ce 0))) out))))
      (:reset-stream (%encode-varints code (getf fields :stream-id 0) (getf fields :application-protocol-error-code 0) (getf fields :final-size 0)))
      (:stop-sending (%encode-varints code (getf fields :stream-id 0) (getf fields :application-protocol-error-code 0)))
      (:crypto (let ((data (ensure-octets (getf fields :data #())))) (%octets (%encode-varints code (getf fields :offset 0) (length data)) data)))
      (:new-token (let ((token (ensure-octets (getf fields :token #())))) (%octets (encode-varint code) (encode-varint (length token)) token)))
      (:stream (let ((data (ensure-octets (getf fields :data #())))) (%octets (encode-varint code) (encode-varint (getf fields :stream-id 0)) (if (getf fields :offset) (encode-varint (getf fields :offset)) #()) (if (getf fields :len-present t) (encode-varint (length data)) #()) data)))
      ((:max-data :max-streams-bidi :max-streams-uni :data-blocked :streams-blocked-bidi :streams-blocked-uni)
       (%encode-varints code (or (getf fields :maximum) (getf fields :limit) (getf fields :stream-id) 0)))
      ((:max-stream-data :stream-data-blocked) (%encode-varints code (getf fields :stream-id 0) (or (getf fields :maximum) (getf fields :limit) 0)))
      (:new-connection-id
       (let ((cid (ensure-octets (getf fields :connection-id #()))) (reset (ensure-octets (getf fields :stateless-reset-token (make-array 16 :element-type '(unsigned-byte 8) :initial-element 0)))))
         (%octets (%encode-varints code (getf fields :sequence 0) (getf fields :retire-prior-to 0)) (vector (length cid)) cid reset)))
      (:retire-connection-id (encode-varint code))
      ((:path-challenge :path-response) (let ((data (ensure-octets (getf fields :data (make-array 8 :element-type '(unsigned-byte 8)))))) (%octets (encode-varint code) data)))
      ((:connection-close :application-close) (%octets (%encode-varints code (getf fields :error-code 0) (if (eq type :connection-close) (getf fields :frame-type 0) 0) (let ((r (or (getf fields :reason #()) #()))) (length r))) (or (getf fields :reason #()) #())))
      (:datagram (let ((data (ensure-octets (getf fields :data #())))) (%octets (encode-varint code) (encode-varint (length data)) data)))
      (otherwise (error 'quic-encoding-error :message "Frame encoding not implemented for this type")))))

(defun decode-frame (bytes &optional (start 0))
  (let* ((b (ensure-octets bytes)) (at start))
    (multiple-value-bind (code next) (decode-varint b at) (setf at next)
      (let ((type (%code-frame code)) (f nil))
        (labels ((v () (multiple-value-bind (x n) (%read-v b at) (setf at n) x))
                 (data (n) (multiple-value-bind (x n2) (%slice b at n) (setf at n2) x)))
          (setf f
                (cond
                  ((= code 0) (make-frame :padding :count 1))
                  ((= code 1) (make-frame :ping))
                  ((member code '(2 3)) (let* ((largest (v)) (delay (v)) (count (v)) (first (v)) (ranges (list (cons largest first)))) (dotimes (i count) (push (list :gap (v) :range-length (v)) ranges)) (make-frame type :largest-acknowledged largest :ack-delay delay :ranges (nreverse ranges))) )
                  ((= code 4) (make-frame :reset-stream :stream-id (v) :application-protocol-error-code (v) :final-size (v)))
                  ((= code 5) (make-frame :stop-sending :stream-id (v) :application-protocol-error-code (v)))
                  ((= code 6) (let ((offset (v)) (n (v))) (make-frame :crypto :offset offset :data (data n))))
                  ((= code 7) (let ((n (v))) (make-frame :new-token :token (data n))))
                  ((<= #x08 code #x0f) (make-frame :stream :stream-id (v) :offset (if (logbitp 2 code) (v) 0) :data (data (if (logbitp 1 code) (v) (- (length b) at))) :fin (logbitp 0 code) :len-present (logbitp 1 code)))
                  ((<= #x10 code #x17) (make-frame type :maximum (v)))
                  ((= code #x18) (let ((seq (v)) (retire (v)) (n (aref b at))) (incf at) (make-frame :new-connection-id :sequence seq :retire-prior-to retire :connection-id (data n) :stateless-reset-token (data 16))))
                  ((= code #x19) (make-frame :retire-connection-id :sequence (v)))
                  ((member code '(#x1a #x1b)) (make-frame type :data (data 8)))
                  ((member code '(#x1c #x1d)) (let ((ec (v)) (ft (if (= code #x1c) (v) 0)) (n (v))) (make-frame type :error-code ec :frame-type ft :reason (data n))))
                  ((= code #x1e) (make-frame :handshake-done))
                  ((= code #x31) (let ((n (v))) (make-frame :datagram :data (data n))))
                  (t (error 'quic-encoding-error :message "Unknown or unsupported QUIC frame type"))))
          (values f at))))))

(defun encode-frames (frames) (apply #'%octets (mapcar #'encode-frame frames)))
(defun decode-frames (bytes &optional (start 0))
  (let ((out '()) (at start))
    (loop while (< at (length bytes)) do (multiple-value-bind (f n) (decode-frame bytes at) (push f out) (setf at n)))
    (nreverse out)))
