(in-package #:cl-quic-kit)

(defun stream-id-direction (id)
  (unless (and (integerp id) (<= 0 id))
    (error 'stream-id-error :stream-id id))
  (if (logbitp 1 id) :unidirectional :bidirectional))

(defun stream-id-initiator (id)
  (unless (and (integerp id) (<= 0 id))
    (error 'stream-id-error :stream-id id))
  (if (zerop (logand id 1)) :client :server))

(defun %stream-octets (data)
  (unless (and (arrayp data) (= (array-rank data) 1)
               (subtypep (array-element-type data) '(unsigned-byte 8)))
    (error 'type-error :datum data :expected-type '(vector (unsigned-byte 8))))
  data)

(defun %copy-octets (data start end)
  (let ((result (make-array (- end start) :element-type '(unsigned-byte 8))))
    (replace result data :start1 0 :start2 start :end2 end)
    result))

(defun %same-octets-p (a b)
  (and (= (length a) (length b))
       (loop for i below (length a) always (= (aref a i) (aref b i)))))

(defstruct (stream (:constructor %make-stream))
  id direction initiator local-p
  (send-offset 0)
  (receive-offset 0)
  (read-offset 0)
  (send-final-size nil)
  (receive-final-size nil)
  (send-max-offset most-positive-fixnum)
  (receive-max-offset most-positive-fixnum)
  (segments nil)
  (receive-ranges nil)
  (read-buffer (make-array 0 :element-type '(unsigned-byte 8)))
  (reset-error-code nil)
  (send-reset-p nil)
  (receive-reset-p nil)
  (stop-error-code nil)
  (send-stop-p nil)
  (receive-stop-p nil)
  (events nil)
  flow-control)

(defun make-stream (id &key (local-initiator :client) flow-control
                              max-send-data max-receive-data)
  (let ((direction (stream-id-direction id))
        (initiator (stream-id-initiator id)))
    (unless (member local-initiator '(:client :server))
      (error 'type-error :datum local-initiator :expected-type '(member :client :server)))
    (when (and max-send-data (< max-send-data 0)) (error 'type-error))
    (when (and max-receive-data (< max-receive-data 0)) (error 'type-error))
    (when (and flow-control (not (typep flow-control 'flow-control-state)))
      (error 'type-error :datum flow-control :expected-type 'flow-control-state))
    (when (and flow-control (not (eq initiator local-initiator)))
      (error 'stream-id-error :stream-id id))
    (%make-stream :id id :direction direction :initiator initiator
                  :local-p (eq initiator local-initiator)
                  :send-max-offset (or max-send-data most-positive-fixnum)
                  :receive-max-offset (or max-receive-data most-positive-fixnum)
                  :flow-control flow-control)))

(defun stream-readable-bytes (stream)
  (length (stream-read-buffer stream)))

(defun stream-reset-p (stream)
  (or (stream-send-reset-p stream) (stream-receive-reset-p stream)))

(defun stream-stopped-p (stream)
  (or (stream-send-stop-p stream) (stream-receive-stop-p stream)))

(defun %queue-event (stream type &rest properties)
  (setf (stream-events stream)
        (nconc (stream-events stream) (list (list* :type type properties))))
  (car (last (stream-events stream))))

(defun stream-pending-events (stream)
  (copy-list (stream-events stream)))

(defun stream-next-event (stream)
  (pop (stream-events stream)))

(defun stream-set-max-send-offset (stream maximum)
  (unless (and (integerp maximum) (>= maximum (stream-send-offset stream)))
    (error 'flow-control-error))
  (when (< maximum (stream-send-max-offset stream))
    (error 'flow-control-error))
  (setf (stream-send-max-offset stream) maximum)
  maximum)

(defun stream-set-max-receive-offset (stream maximum)
  (unless (and (integerp maximum) (>= maximum (stream-receive-offset stream)))
    (error 'flow-control-error))
  (when (< maximum (stream-receive-max-offset stream))
    (error 'flow-control-error))
  (setf (stream-receive-max-offset stream) maximum)
  maximum)

(defun stream-write (stream data)
  (%stream-octets data)
  (unless (stream-local-p stream) (error 'stream-id-error :stream-id (stream-id stream)))
  (when (or (stream-send-final-size stream) (stream-send-reset-p stream)
            (stream-receive-stop-p stream))
    (error 'flow-control-error))
  (let* ((size (length data))
         (end (+ (stream-send-offset stream) size)))
    (when (> end (stream-send-max-offset stream))
      (%queue-event stream :stream-data-blocked :limit (stream-send-max-offset stream)
                    :offset end)
      (%raise-limit (stream-send-max-offset stream) end))
    (when (stream-flow-control stream)
      (handler-case
          (flow-control-reserve-send (stream-flow-control stream) size)
        (flow-control-limit-error (condition)
          (%queue-event stream :data-blocked
                        :limit (flow-control-error-limit condition)
                        :offset (flow-control-error-attempted condition))
          (error condition))))
    (incf (stream-send-offset stream) size)
    (list :offset (- (stream-send-offset stream) size) :data data :fin nil)))

(defun stream-finish (stream)
  (when (or (stream-send-final-size stream) (stream-send-reset-p stream))
    (error 'flow-control-error))
  (setf (stream-send-final-size stream) (stream-send-offset stream))
  (%queue-event stream :fin :offset (stream-send-offset stream)))

(defun stream-reset-send (stream error-code)
  (%non-negative-integer error-code :error-code)
  (when (or (stream-send-final-size stream) (stream-send-reset-p stream))
    (error 'flow-control-error))
  (setf (stream-reset-error-code stream) error-code)
  (setf (stream-send-reset-p stream) t)
  (%queue-event stream :reset-stream :error-code error-code
                :final-size (stream-send-offset stream)))

(defun stream-stop-sending (stream error-code)
  (%non-negative-integer error-code :error-code)
  (setf (stream-stop-error-code stream) error-code)
  (setf (stream-send-stop-p stream) t)
  (%queue-event stream :stop-sending :error-code error-code))

(defun stream-reset-receive (stream error-code final-size)
  (%non-negative-integer error-code :error-code)
  (%non-negative-integer final-size :final-size)
  (when (and (stream-receive-final-size stream)
             (/= final-size (stream-receive-final-size stream)))
    (error 'flow-control-error))
  (when (< final-size (stream-receive-offset stream))
    (error 'flow-control-error))
  (when (some (lambda (range) (> (cdr range) final-size))
              (stream-receive-ranges stream))
    (error 'flow-control-error))
  (setf (stream-receive-final-size stream) final-size
        (stream-reset-error-code stream) error-code
        (stream-receive-reset-p stream) t)
  (%queue-event stream :reset-stream :error-code error-code :final-size final-size))

(defun stream-stop-sending-receive (stream error-code)
  (%non-negative-integer error-code :error-code)
  (setf (stream-stop-error-code stream) error-code
        (stream-receive-stop-p stream) t)
  (%queue-event stream :stop-sending :error-code error-code))

(defun %merge-segments (previous current)
  (let* ((previous-start (car previous))
         (previous-data (cdr previous))
         (previous-end (+ previous-start (length previous-data)))
         (current-start (car current))
         (current-data (cdr current))
         (current-end (+ current-start (length current-data))))
    (if (> current-start previous-end)
        (values previous t)
        (progn
          (when (and (< current-start previous-end)
                     (not (%same-octets-p
                           (subseq previous-data (- current-start previous-start)
                                   (min (length previous-data)
                                        (- current-end previous-start)))
                           (subseq current-data 0
                                   (min (length current-data)
                                        (- previous-end current-start))))))
            (error 'flow-control-error))
          (values (if (> current-end previous-end)
                      (cons previous-start
                            (concatenate '(vector (unsigned-byte 8))
                                         previous-data
                                         (subseq current-data
                                                 (- previous-end current-start))))
                      previous)
                  nil)))))

(defun %insert-segment (stream start data)
  (when (zerop (length data))
    (return-from %insert-segment stream))
  (let ((all (sort (cons (cons start data) (copy-list (stream-segments stream)))
                   #'< :key #'car))
        (result nil))
    (dolist (segment all)
      (if (null result)
          (push (cons (car segment) (copy-seq (cdr segment))) result)
            (multiple-value-bind (merged separate)
              (%merge-segments (car result) segment)
            (if separate
                (push (cons (car segment) (copy-seq (cdr segment))) result)
                (setf (car result) merged)))))
    (setf (stream-segments stream) (nreverse result))))

(defun %validate-segment (stream start data)
  (let ((end (+ start (length data))))
    (dolist (segment (stream-segments stream))
      (let* ((segment-start (car segment))
             (segment-data (cdr segment))
             (segment-end (+ segment-start (length segment-data)))
             (from (max start segment-start))
             (to (min end segment-end)))
        (loop for position from from below to
              unless (= (aref data (- position start))
                        (aref segment-data (- position segment-start)))
                do (error 'flow-control-error))))))

(defun %range-new-length (ranges start end)
  (let ((covered 0))
    (dolist (range ranges)
      (let ((from (max start (car range)))
            (to (min end (cdr range))))
        (when (< from to) (incf covered (- to from)))))
    (- (- end start) covered)))

(defun %insert-range (ranges start end)
  (let ((all (sort (cons (cons start end) (copy-list ranges)) #'< :key #'car))
        (result nil))
    (dolist (range all)
      (if (and result (<= (car range) (cdr (car result))))
          (setf (cdr (car result)) (max (cdr (car result)) (cdr range)))
          (push (cons (car range) (cdr range)) result)))
    (nreverse result)))

(defun %drain-contiguous (stream)
  (loop while (stream-segments stream)
        for segment = (first (stream-segments stream))
        for start = (car segment)
        for data = (cdr segment)
        while (= start (stream-receive-offset stream))
        do (setf (stream-segments stream) (rest (stream-segments stream)))
           (setf (stream-read-buffer stream)
                 (concatenate '(vector (unsigned-byte 8))
                              (stream-read-buffer stream) data))
           (incf (stream-receive-offset stream) (length data))))

(defun stream-receive-data (stream offset data &key fin)
  (%non-negative-integer offset :offset)
  (%stream-octets data)
  (when (and (eq (stream-direction stream) :unidirectional)
             (stream-local-p stream))
    (error 'stream-id-error :stream-id (stream-id stream)))
  (when (stream-receive-stop-p stream)
    (return-from stream-receive-data
      (list :offset offset :length (length data) :fin (not (null fin)) :discarded t)))
  (let ((end (+ offset (length data))))
    (when (> end (stream-receive-max-offset stream))
      (%raise-limit (stream-receive-max-offset stream) end))
    (when (stream-receive-final-size stream)
      (when (> end (stream-receive-final-size stream))
        (error 'flow-control-error)))
    (when fin
      (when (< end (stream-receive-offset stream))
        (error 'flow-control-error))
      (when (some (lambda (range) (> (cdr range) end))
                  (stream-receive-ranges stream))
        (error 'flow-control-error))
      (when (and (stream-receive-final-size stream)
                 (/= (stream-receive-final-size stream) end))
        (error 'flow-control-error)))
    (let ((stored-start (max offset (stream-receive-offset stream)))
          (stored-data (cond
                         ((<= end (stream-receive-offset stream))
                          (make-array 0 :element-type '(unsigned-byte 8)))
                         ((< offset (stream-receive-offset stream))
                          (subseq data (- (stream-receive-offset stream) offset)))
                         (t (copy-seq data)))))
      (when (plusp (length stored-data))
        (%validate-segment stream stored-start stored-data)))
    (let ((new-bytes (%range-new-length (stream-receive-ranges stream) offset end)))
      (when (and (> new-bytes 0) (stream-flow-control stream))
        (flow-control-note-received (stream-flow-control stream) new-bytes))
      (when (< offset end)
        (setf (stream-receive-ranges stream)
              (%insert-range (stream-receive-ranges stream) offset end))))
    (when fin
      (setf (stream-receive-final-size stream) end))
    (when (> end (stream-receive-offset stream))
      (%insert-segment stream (max offset (stream-receive-offset stream))
                       (if (< offset (stream-receive-offset stream))
                           (subseq data (- (stream-receive-offset stream) offset))
                           (copy-seq data))))
    (%drain-contiguous stream)
    (list :offset offset :length (length data) :fin (not (null fin)))))

(defun stream-read (stream &optional (maximum most-positive-fixnum))
  (%non-negative-integer maximum :maximum)
  (let* ((count (min maximum (length (stream-read-buffer stream))))
         (data (%copy-octets (stream-read-buffer stream) 0 count)))
    (setf (stream-read-buffer stream)
          (%copy-octets (stream-read-buffer stream) count
                        (length (stream-read-buffer stream))))
    (incf (stream-read-offset stream) count)
    (values data (and (zerop (length (stream-read-buffer stream)))
                      (stream-receive-final-size stream)
                      (= (stream-receive-offset stream)
                         (stream-receive-final-size stream))))))

(defun stream-finished-p (stream)
  (and (zerop (length (stream-read-buffer stream)))
       (stream-receive-final-size stream)
       (= (stream-receive-offset stream) (stream-receive-final-size stream))))
