name: CI

on:
  push:
  pull_request:

jobs:
  bootstrap:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v30
      - run: nix flake check --all-systems --no-write-lock-file
      - run: nix develop --command sbcl --non-interactive --load t/run.lisp
