name: CI

on:
  push:
  pull_request:

jobs:
  nix-flake-check:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v20
      - run: nix flake check --all-systems --no-build
      - run: nix flake check
